export const allProducts = [
  {
    id: 1,
    pickItem: false,
    itemName: "Strip T-Shirt",
    img: "https://i.ibb.co/kMhN102/tshirt.jpg",
    price: 1200,
    quantity: 1,
    catagory: "men",
    rating: 5,
    rank: "regular",
    about:
      "egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae",
    desc: "turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam faucibus purus in massa tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus",
  },
  {
    id: 2,
    pickItem: false,
    itemName: "Soft T-Shirt",
    img: "https://i.ibb.co/jhV9tyQ/tshirt1.jpg",
    price: 1250,
    quantity: 1,
    catagory: "men",
    rating: 4.5,
    rank: "regular",
    about:
      "egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae",
    desc: "turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam faucibus purus in massa tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus",
  },
  {
    id: 3,
    pickItem: false,
    itemName: "Gent's Formal Shirt (Mint)",
    img: "https://i.ibb.co/WFZXF9Q/formal-shirt.jpg",
    price: 1400,
    quantity: 1,
    catagory: "men",
    rating: 5,
    rank: "trendy",
    about:
      "egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae",
    desc: "turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam faucibus purus in massa tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus",
  },
  {
    id: 4,
    pickItem: false,
    itemName: "Red Formal T-Shirt",
    img: "https://i.ibb.co/m0pzNyN/formal-shirt1.jpg",
    price: 1300,
    quantity: 1,
    catagory: "men",
    rating: 4,
    rank: "regular",
    about:
      "egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae",
    desc: "turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam faucibus purus in massa tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus",
  },
];
